/**
 * @file line_separator.h
 * @author DuYicheng
 * @date 2025-10-04
 * @brief 换行符
 */

#pragma once
#ifndef EMDEVIF_LINE_SEPARATOR_H
#define EMDEVIF_LINE_SEPARATOR_H

#define EMDEVIF_LINE_SEPARATOR_CRLF      "\r\n"
#define EMDEVIF_LINE_SEPARATOR_LF        "\n"
#define EMDEVIF_LINE_SEPARATOR_CR        "\r"

#define EMDEVIF_LINE_SEPARATOR_MODE_CRLF 0
#define EMDEVIF_LINE_SEPARATOR_MODE_LF   1
#define EMDEVIF_LINE_SEPARATOR_MODE_CR   2

#ifndef EMDEVIF_LINE_SEPARATOR_MODE
#define EMDEVIF_LINE_SEPARATOR_MODE EMDEVIF_LINE_SEPARATOR_MODE_CRLF
#endif

#if (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_CRLF)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_CRLF
#elif (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_LF)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_LF
#elif (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_CR)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_CR
#endif

#endif  // !EMDEVIF_LINE_SEPARATOR_H
